# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: a2d-controller-manager
    app.kubernetes.io/name: alert2dash-operator
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager-monitor
  namespace: system
spec:
  endpoints:
    - path: /metrics
      port: mertrics
  selector:
    matchLabels:
      control-plane: a2d-controller-manager
