apiVersion: v1
kind: Service
metadata:
  name: controller-manager-service
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: alert2dash-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: metrics
  selector:
    control-plane: controller-manager
