apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: alert2dash-operator
    app.kubernetes.io/managed-by: kustomize
  name: le-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election
subjects:
- kind: ServiceAccount
  name: ctrl-mngr-sa
  namespace: system
